//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChessPlatform.ComputerPlayers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChessPlatform.ComputerPlayers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b1c3g8f6d2d4d7d6c1g5b8d7e2e4g7g6f2f4h7h6g5h4f6h5g1e2g6g5f4g5e7e6e2g3h5f4
        ///b1c3g8f6d2d4d7d6e2e4g7g6f1c4f8g7f2f4c7c5d4c5d8a5c1d2a5c5d1e2e8g8e1c1c8g4g1f3b8d7
        ///b1c3g8f6e2e4d7d6d2d4g7g6f1c4f8g7g1f3e8g8e4e5d6e5d4e5d8d1c3d1f6g4c1f4b8c6e5e6c8e6
        ///b1c3g8f6g1f3g7g6d2d4d7d6e2e4f8g7f1e2e8g8h2h3c7c5d4c5d8a5e1g1a5c5c1e3c5a5f3d4a7a6
        ///b1c3g8f6g1f3g7g6e2e4d7d6d2d4f8g7f1e2e8g8c1f4b8c6d4d5e7e5f4g5c6e7d1d2f6h5e1c1
        ///b2b3e7e5c1b2b8c6c2c4g8f6b1c3d7d5c4d5f6d5g1f3d5c3b2c3f8d6d2d3e8g8e2e3d8e7f1e2c8d7
        ///b2b3e7e5c1b2b8c6c2c4g8f6e2e3d7d5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpeningBook {
            get {
                return ResourceManager.GetString("OpeningBook", resourceCulture);
            }
        }
    }
}
